changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: "What's new 🎉"
      labels:
        - enhancement
    - title: Bugfixes 🪲
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
