package cz.jaro.dpmcb.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF626200)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFeaea00)
val md_theme_light_onPrimaryContainer = Color(0xFF1d1d00)
val md_theme_light_secondary = Color(0xFF616043)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe6e4bf)
val md_theme_light_onSecondaryContainer = Color(0xFF1d1c06)
val md_theme_light_tertiary = Color(0xFF3d6656)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc0ecd8)
val md_theme_light_onTertiaryContainer = Color(0xFF002116)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffcf2)
val md_theme_light_onBackground = Color(0xFF1c1c16)
val md_theme_light_surface = Color(0xFFfffcf2)
val md_theme_light_onSurface = Color(0xFF1c1c16)
val md_theme_light_surfaceVariant = Color(0xFFe6e3d1)
val md_theme_light_onSurfaceVariant = Color(0xFF48473a)
val md_theme_light_outline = Color(0xFF797769)
val md_theme_light_inverseOnSurface = Color(0xFFf4f0e8)
val md_theme_light_inverseSurface = Color(0xFF31302b)
val md_theme_light_inversePrimary = Color(0xFFcdcd00)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFcdcd00)
val md_theme_dark_onPrimary = Color(0xFF323200)
val md_theme_dark_primaryContainer = Color(0xFF4a4900)
val md_theme_dark_onPrimaryContainer = Color(0xFFeaea00)
val md_theme_dark_secondary = Color(0xFFcac8a5)
val md_theme_dark_onSecondary = Color(0xFF323218)
val md_theme_dark_secondaryContainer = Color(0xFF48482d)
val md_theme_dark_onSecondaryContainer = Color(0xFFe6e4bf)
val md_theme_dark_tertiary = Color(0xFFa4d0bd)
val md_theme_dark_onTertiary = Color(0xFF0b372a)
val md_theme_dark_tertiaryContainer = Color(0xFF254e40)
val md_theme_dark_onTertiaryContainer = Color(0xFFc0ecd8)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1c1c16)
val md_theme_dark_onBackground = Color(0xFFe6e2da)
val md_theme_dark_surface = Color(0xFF1c1c16)
val md_theme_dark_onSurface = Color(0xFFe6e2da)
val md_theme_dark_surfaceVariant = Color(0xFF48473a)
val md_theme_dark_onSurfaceVariant = Color(0xFFcac7b6)
val md_theme_dark_outline = Color(0xFF939182)
val md_theme_dark_inverseOnSurface = Color(0xFF1c1c16)
val md_theme_dark_inverseSurface = Color(0xFFe6e2da)
val md_theme_dark_inversePrimary = Color(0xFF626200)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFFffff00)
val error = Color(0xFFba1b1b)
