name: Build & Publish Debug APK

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Generate version.txt file
        run: ./gradlew generateVersionTxt
      - name: Get version name
        run: VERSION_NAME="v$(cat ./app/version.txt)"
      - name: Create git tag
        run: git tag "${VERSION_NAME}"
      - name: push git tag
        run: git push origin --tags
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/debug/*-debug.apk"
          commit: "beta"
          generateReleaseNotes: true
          tag: ${{ env.VERSION_NAME }}
          
