name: Build & Publish Signed Release APK

on:
  push:
    branches:
      - beta
      - CI

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Get version name
        run: echo "VERSION_NAME=v$(cat ./app/version.txt)" >> $GITHUB_ENV
      - name: Create git tag
        run: |
          git fetch --tags
          git tag "v$(cat ./app/version.txt)"
      - name: Build Signed APK
        uses: victorbnl/build-signed-apk@main
        with:
          keystore_b64: ${{ secrets.keystore }}
          keystore_password: ${{ secrets.keystore_password }}
          key_alias: ${{ secrets.key_alias }}
          key_password: ${{ secrets.key_password }}
      - name: Push git tag
        run: |
          git config --global user.name 'jaro-jaro'
          git config --global user.email 'jaro-jaro@users.noreply.github.com'
          git push --tags
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/release/app-release.apk"
          commit: "beta"
          generateReleaseNotes: true
          tag: ${{ env.VERSION_NAME }}
          makeLatest: false
          
