name: Build Debug APK

on:
  push

jobs:
  build:
    name: Debug APK
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Get version name
        run: echo "VERSION_NAME=v$(cat ./app/version.txt)" >> $GITHUB_ENV
      - name: Build APK
        run: ./gradlew assembleDebug
      - name: Rename APK
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          mv app/build/outputs/apk/debug/app-debug.apk "app/build/outputs/apk/debug/Lepší-DPMCB-DEBUG-branch-$(echo ${BRANCH_NAME//\//\-}).apk"
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk