name: Build Debug APK

on:
  push

jobs:
  build:
    name: Debug APK
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Get version name
        run: echo "VERSION_NAME=v$(cat ./composeApp/version.txt)" >> $GITHUB_ENV
      - name: Write keystore file from content
        run: echo "${{ secrets.keystore }}" | base64 -d > "$GITHUB_WORKSPACE/signing-key.jks"
      - name: Build APK
        run: |
          ./gradlew build --no-daemon
          ./gradlew assembleDebug --no-daemon \
            -Pandroid.injected.signing.store.file="$GITHUB_WORKSPACE/signing-key.jks" \
            -Pandroid.injected.signing.store.password="${{ secrets.keystore_password }}" \
            -Pandroid.injected.signing.key.alias="${{ secrets.key_alias }}" \
            -Pandroid.injected.signing.key.password="${{ secrets.key_password }}"
      - name: Remove keystore
        run: rm "$GITHUB_WORKSPACE/signing-key.jks"
      - name: Build APK
        run: ./gradlew assembleDebug
      - name: Rename APK
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          mv composeApp/build/outputs/apk/debug/composeApp-debug.apk "composeApp/build/outputs/apk/debug/Lepší-DPMCB-DEBUG-branch-$(echo ${BRANCH_NAME//\//\-}).apk"
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: composeApp/build/outputs/apk/debug/*.apk