name: Build Debug APK for other branches

on:
  push:
    branches-ignore:
      - main
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Save keystore file
        run: echo "${{ secrets.keystore }}" | base64 -d > $GITHUB_WORKSPACE/signing-key.jks
      - run: cat $GITHUB_WORKSPACE/signing-key.jks
      - run: echo $GITHUB_WORKSPACE/signing-key.jks
      - name: Build
        run: ./gradlew build
      - name: Generate signed debug apk
        run: ./gradlew assembleDebug \
          -Pandroid.injected.signing.store.file="$GITHUB_WORKSPACE/signing-key.jks" \
          -Pandroid.injected.signing.store.password=${{ secrets.keystore_password }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.key_alias }} \
          -Pandroid.injected.signing.key.password=${{ secrets.key_password }}
      - name: Commit and push
        run: |
          git add app/build/outputs/apk/debug/app-debug.apk
          git commit -m "Generated debug APK"
          git push