name: Build Debug APK for other branches

on:
  push:
    branches-ignore:
      - main
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Generate signed debug apk
        run: ./gradlew assembleDebug
      - name: Sign APK
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/debug
          signingKey: ${{ secrets.keystore }}
          keyAlias: ${{ secrets.key_alias }}
          keyStorePassword: ${{ secrets.keystore_password }}
          keyPassword: ${{ secrets.key_password }}
          buildToolsVersion: 33.0.0
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f app/build/outputs/apk/debug/app-debug-signed.apk
          git commit -m "Generated debug APK"
          git push
